services:
  api:
    build: 
      context: ./api
    container_name: churn_api
    ports:
      - "8000:8000"
    #volumes:
     # - ./models:/app/models  # Mount models so API can load them
      #- ./housing_pipeline.py:/app/housing_pipeline.py # Mount pipeline

  streamlit:
    build: 
      context: ./streamlit_app
    container_name: churn_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
   # volumes:
    #  - ./data:/app/data  # Mount data so UI can read schema.json